/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab1_camiloferrera;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Camilo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_tipoestudiante.getModel();
        modelo.addElement("Estudiante Normal");
        modelo.addElement("Tutor");
        cb_tipoestudiante.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_contraseñaregistro = new javax.swing.JPasswordField();
        cb_tipoestudiante = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreregistro = new javax.swing.JTextField();
        tf_nombreusuarioregistro = new javax.swing.JTextField();
        tf_numerocuenta = new javax.swing.JTextField();
        tf_nacimiento = new javax.swing.JTextField();
        tf_carrera = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel_RegistroFondo = new javax.swing.JLabel();
        CrearExamen = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sp_cepuntaje = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        tf_cetema = new javax.swing.JTextField();
        tf_ceclase = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_iqcrearexamen = new javax.swing.JTextField();
        jLabel_CrearExamenFondo = new javax.swing.JLabel();
        Menu = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaexamenesp = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cb_tutores = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JPasswordField();
        tf_nombreusuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel_fondo = new javax.swing.JLabel();

        Registro.setResizable(false);
        Registro.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                RegistroWindowClosing(evt);
            }
        });
        Registro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Tipo de Estudiante:");
        Registro.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        Registro.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Edad:");
        Registro.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Carrera:");
        Registro.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Lugar Nacimiento:");
        Registro.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Numero de Cuenta:");
        Registro.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 290, 140, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Nombre de Usuario:");
        Registro.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 30));
        Registro.getContentPane().add(tf_contraseñaregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 140, 30));
        Registro.getContentPane().add(cb_tipoestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 140, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Contraseña:");
        Registro.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 20));
        Registro.getContentPane().add(tf_nombreregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, 30));
        Registro.getContentPane().add(tf_nombreusuarioregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 140, 30));
        Registro.getContentPane().add(tf_numerocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 140, 30));
        Registro.getContentPane().add(tf_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 140, 30));
        Registro.getContentPane().add(tf_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, 30));

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, 99, 1));
        Registro.getContentPane().add(sp_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 30));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Siguiente");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        Registro.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 110, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel11.setText("REGISTRO");
        Registro.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));
        Registro.getContentPane().add(jLabel_RegistroFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 570));

        CrearExamen.setResizable(false);
        CrearExamen.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                CrearExamenWindowDeactivated(evt);
            }
        });
        CrearExamen.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Clase:");
        CrearExamen.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Tema:");
        CrearExamen.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Puntaje:");
        CrearExamen.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        sp_cepuntaje.setModel(new javax.swing.SpinnerNumberModel(5, 5, 100, 5));
        CrearExamen.getContentPane().add(sp_cepuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 50, 30));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setText("Crear Examen");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        CrearExamen.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));
        CrearExamen.getContentPane().add(tf_cetema, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, 30));
        CrearExamen.getContentPane().add(tf_ceclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("IQ Requerido: ");
        CrearExamen.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));
        CrearExamen.getContentPane().add(tf_iqcrearexamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 50, 30));
        CrearExamen.getContentPane().add(jLabel_CrearExamenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 330));

        Menu.setResizable(false);
        Menu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("ModificarDatos", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar Nac.", "Num. Cuenta", "Usuario", "Contraseña", "Conocimiento", "Nivel Aprend."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(5).setResizable(false);
            tabla.getColumnModel().getColumn(6).setResizable(false);
            tabla.getColumnModel().getColumn(7).setResizable(false);
            tabla.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 510));

        jTabbedPane1.addTab("ListarDatos", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaexamenesp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clase", "IQ Requerido", "Tema", "Puntaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaexamenesp);
        if (tablaexamenesp.getColumnModel().getColumnCount() > 0) {
            tablaexamenesp.getColumnModel().getColumn(0).setResizable(false);
            tablaexamenesp.getColumnModel().getColumn(1).setResizable(false);
            tablaexamenesp.getColumnModel().getColumn(2).setResizable(false);
            tablaexamenesp.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 510));

        jTabbedPane1.addTab("ExamenesPendientes", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("ExamenesResueltos", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("Tutor:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("Hora:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setText("Aula:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel21.setText("Fecha:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel22.setText("Tema:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));
        jPanel5.add(cb_tutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 66, 190, 40));

        jTabbedPane1.addTab("ReservarTutoria", jPanel5);
        jTabbedPane1.addTab("HacerExamen", jPanel6);
        jTabbedPane1.addTab("DarTutoria", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel23.setText("¿Seguro que quiere Salir?");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 470, -1));

        jButton6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton6.setText("SI");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 270, 120));

        jTabbedPane1.addTab("Salir", jPanel8);

        Menu.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 540));
        Menu.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 810, 540));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Nombre de Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        getContentPane().add(tf_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 140, 30));
        getContentPane().add(tf_nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, 30));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Registrarse");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 120, 40));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 130, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel12.setText("INICIO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setText("Crear Examen");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 140, 40));
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Registro.pack();
        Registro.setLocationRelativeTo(null);
        Registro.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            if (tf_nombreregistro.getText().isEmpty() == true || tf_carrera.getText().isEmpty() == true || tf_nacimiento.getText().isEmpty() == true || tf_numerocuenta.getText().isEmpty() == true || tf_nombreusuarioregistro.getText().isEmpty() == true || tf_contraseñaregistro.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(Registro, "Hay casillas vacias");           
            } else {
                String nombre = tf_nombreregistro.getText();
                int edad = (Integer)sp_edad.getValue();
                String carrera = tf_carrera.getText();
                String lugar = tf_nacimiento.getText();
                String num = tf_numerocuenta.getText();
                String user = tf_nombreusuarioregistro.getText();
                String pass = tf_contraseñaregistro.getText();

                if (cb_tipoestudiante.getSelectedIndex() == 0) {
                    int nivel = Integer.parseInt(JOptionPane.showInputDialog("Ingrese Nivel de Aprendizaje:"));
                    alumnos.add(new EstudianteNormal (nivel,nombre,carrera,lugar,num,user,pass,edad));
                    JOptionPane.showMessageDialog(Registro,"Estudiante Normal creado con exito");
                    Registro.setVisible(false);
                    tf_nombreregistro.setText("");
                    sp_edad.setValue(18);
                    tf_carrera.setText("");
                    tf_nacimiento.setText("");
                    tf_numerocuenta.setText("");
                    tf_nombreusuarioregistro.setText("");
                    tf_contraseñaregistro.setText("");
                    cb_tipoestudiante.setSelectedIndex(0);
                } else if (cb_tipoestudiante.getSelectedIndex() == 1){
                    int nivel = Integer.parseInt(JOptionPane.showInputDialog("Ingrese Nivel de Enseñanza:"));
                    int n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese numero de clases que imparte:"));
                    ArrayList<String> clases = new ArrayList ();
                    int cont = 1;
                    for (int i = 0; i < n ; i++) {
                        clases.add(JOptionPane.showInputDialog("Ingrese clase #" + cont + ":"));
                        cont++;
                    }
                    Tutor x = new Tutor (nivel,nombre,carrera,lugar,num,user,pass,edad);
                    x.setClases(clases);
                    alumnos.add(x);
                    JOptionPane.showMessageDialog(Registro,"Tutor creado con exito");
                    Registro.setVisible(false);
                    tf_nombreregistro.setText("");
                    sp_edad.setValue(18);
                    tf_carrera.setText("");
                    tf_nacimiento.setText("");
                    tf_numerocuenta.setText("");
                    tf_nombreusuarioregistro.setText("");
                    tf_contraseñaregistro.setText("");
                    cb_tipoestudiante.setSelectedIndex(0);
                }
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Registro, "Hubo un error, contacte al administrador");
            tf_nombreregistro.setText("");
            sp_edad.setValue(18);
            tf_carrera.setText("");
            tf_nacimiento.setText("");
            tf_numerocuenta.setText("");
            tf_nombreusuarioregistro.setText("");
            tf_contraseñaregistro.setText("");
            cb_tipoestudiante.setSelectedIndex(0);
        }
               
    }//GEN-LAST:event_jButton3MouseClicked

    private void RegistroWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegistroWindowClosing
        // TODO add your handling code here:
        tf_nombreregistro.setText("");
        sp_edad.setValue(18);
        tf_carrera.setText("");
        tf_nacimiento.setText("");
        tf_numerocuenta.setText("");
        tf_nombreusuarioregistro.setText("");
        tf_contraseñaregistro.setText("");
        cb_tipoestudiante.setSelectedIndex(0);
    }//GEN-LAST:event_RegistroWindowClosing

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        CrearExamen.pack();
        CrearExamen.setLocationRelativeTo(this);
        CrearExamen.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
            if (tf_ceclase.getText().isEmpty() == true || tf_cetema.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(CrearExamen, "Hay campos vacios.");
            } else {
                String clase = tf_ceclase.getText();
                String tema = tf_cetema.getText();
                int p = (Integer) sp_cepuntaje.getValue();
                int iq = Integer.parseInt(tf_iqcrearexamen.getText());
                System.out.println(iq);

                Examen x = new Examen(clase,tema,iq,p);
                for (int i = 0; i < alumnos.size(); i++) {
                    if (alumnos.get(i) instanceof EstudianteNormal) {
                        ((EstudianteNormal)alumnos.get(i)).getExamenes().add(x);
                    }
                }

                JOptionPane.showMessageDialog(CrearExamen, "Examen creado con exito!");
                CrearExamen.setVisible(false);
                tf_ceclase.setText("");
                tf_cetema.setText("");
                tf_iqcrearexamen.setText("");
                sp_cepuntaje.setValue(5);
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(CrearExamen, "Hubo un error, contacte al administrador");
            tf_ceclase.setText("");
            tf_cetema.setText("");
            tf_iqcrearexamen.setText("");
            sp_cepuntaje.setValue(5);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void CrearExamenWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_CrearExamenWindowDeactivated
        // TODO add your handling code here:
        tf_ceclase.setText("");
        tf_cetema.setText("");
        tf_iqcrearexamen.setText("");
        sp_cepuntaje.setValue(5);
    }//GEN-LAST:event_CrearExamenWindowDeactivated

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            if (tf_nombreusuario.getText().isEmpty() == true || tf_contraseña.getText().isEmpty() == true) {
                JOptionPane.showInputDialog(this,"Hay campos vacios");
            } else {
                String username = tf_nombreusuario.getText();
                String pass = tf_contraseña.getText();

                boolean valido = false;
                for (int i = 0; i < alumnos.size(); i++) {
                    if (alumnos.get(i).getUsuario().equals(username) && alumnos.get(i).getContraseña().equals(pass)) {
                        valido = true;
                        this.flag = i;
                        break;
                    }
                }
                
                if (valido == true) {
                    tf_nombreusuario.setText("");
                    tf_contraseña.setText("");
                    DefaultComboBoxModel cb = (DefaultComboBoxModel) cb_tutores.getModel();
                    for (int i = 0; i < alumnos.size(); i++) {
                        if (alumnos.get(i) instanceof Tutor) {
                            cb.addElement(alumnos.get(i));
                        }
                    }
                    cb_tutores.setModel(cb);
                    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
                    for (int i = 0; i < alumnos.size(); i++) {
                        if (alumnos.get(i) instanceof EstudianteNormal) {
                            Object[] row = {alumnos.get(i),alumnos.get(i).getEdad(),alumnos.get(i).getCarrera(),alumnos.get(i).getLugarnacimiento(),
                            alumnos.get(i).getNumerocuenta(),alumnos.get(i).getUsuario(),alumnos.get(i).getContraseña(),((EstudianteNormal)alumnos.get(i)).getConocimientoacumulado(),((EstudianteNormal)alumnos.get(i)).getNiveldeaprendizaje()};
                            modelo.addRow(row);
                        }
                    }
                    tabla.setModel(modelo);
                    
                    Menu.pack();
                    Menu.setLocationRelativeTo(null);
                    Menu.setVisible(true);
                    this.setVisible(false);
                    if (alumnos.get(this.flag) instanceof EstudianteNormal) {
                        modelo = (DefaultTableModel)tablaexamenesp.getModel();
                        for (int i = 0; i < ((EstudianteNormal)alumnos.get(flag)).getExamenes().size(); i++) {
                            Object[] row = {((EstudianteNormal) alumnos.get(flag)).getExamenes().get(i).getClase(),((EstudianteNormal) alumnos.get(flag)).getExamenes().get(i).getIqrequerido(),
                            ((EstudianteNormal) alumnos.get(flag)).getExamenes().get(i).getTema(), ((EstudianteNormal) alumnos.get(flag)).getExamenes().get(i).getPuntaje()};
                            modelo.addRow(row);
                        }
                        tablaexamenesp.setModel(modelo);                       
                        jTabbedPane1.setEnabledAt(6, false);
                    } else {
                        jTabbedPane1.setEnabledAt(2, false);
                        jTabbedPane1.setEnabledAt(3, false);
                        jTabbedPane1.setEnabledAt(4, false);
                        jTabbedPane1.setEnabledAt(5, false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,"Nombre de usuario y/o contraseña incorrecto/s");
                    tf_nombreusuario.setText("");
                    tf_contraseña.setText("");
                }
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hubo un error contacte al administrador.");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        Menu.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        alumnos.add(new EstudianteNormal (99,"Camilo","Sistemas","TGU","11841136","camiloeferrera","java123",19));
        alumnos.add(new Tutor (99,"Diego","Sistemas","SPS","11156745","diegom","java123",22));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CrearExamen;
    private javax.swing.JFrame Menu;
    private javax.swing.JFrame Registro;
    private javax.swing.JComboBox<String> cb_tipoestudiante;
    private javax.swing.JComboBox<String> cb_tutores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_CrearExamenFondo;
    private javax.swing.JLabel jLabel_RegistroFondo;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner sp_cepuntaje;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaexamenesp;
    private javax.swing.JTextField tf_carrera;
    private javax.swing.JTextField tf_ceclase;
    private javax.swing.JTextField tf_cetema;
    private javax.swing.JPasswordField tf_contraseña;
    private javax.swing.JPasswordField tf_contraseñaregistro;
    private javax.swing.JTextField tf_iqcrearexamen;
    private javax.swing.JTextField tf_nacimiento;
    private javax.swing.JTextField tf_nombreregistro;
    private javax.swing.JTextField tf_nombreusuario;
    private javax.swing.JTextField tf_nombreusuarioregistro;
    private javax.swing.JTextField tf_numerocuenta;
    // End of variables declaration//GEN-END:variables
    public static ArrayList <Alumno> alumnos = new ArrayList();
    
    private int flag;
}
